uploads = []

[[generated]]
id = "Qk3EHx01v56ZyNX-zTExQ"
uri = "file://exports/truck-wrap/f250-side-profile.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HH3lGzCWodeTOeJdZPAQ4"
uri = "file://exports/truck-wrap/f250-three-quarter.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gTzL6CzCMQNNKqRGMryfk"
uri = "file://exports/truck-wrap/f250-rear-tailgate.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "zv2v1Pv208sUuWTkO3Y8S"
uri = "file://exports/email-signature/landon-co-logo-black-120.png"
type = "image"
title = "Black logo — 120px display (240px @ 2x)"

[[outputs]]
id = "8usPfM42BCB6RHcPfWKRH"
uri = "file://exports/email-signature/landon-co-logo-black-200.png"
type = "image"
title = "Black logo — 200px display (400px @ 2x)"

[[outputs]]
id = "d53_iIwLFsjEosw66k3jm"
uri = "file://exports/email-signature/landon-co-logo-white-120.png"
type = "image"
title = "White logo — 120px display (240px @ 2x)"

[[outputs]]
id = "cDvmjvKIYaEd1ISzqpNuy"
uri = "file://exports/email-signature/landon-co-logo-white-200.png"
type = "image"
title = "White logo — 200px display (400px @ 2x)"

[[outputs]]
id = "P5mJCBzZk3ldohSVmGt6U"
uri = "file://exports/truck-wrap/f250-three-quarter.png"
type = "image"
title = "F-250 Wrap Mockup — 3/4 Front Angle"

[[outputs]]
id = "dxaPmVfE8q7uQTogGMuPs"
uri = "file://exports/truck-wrap/f250-side-profile.png"
type = "image"
title = "F-250 Wrap Mockup — Side Profile"

[[outputs]]
id = "Xw_vu6CQUO4PV-7_ykVQs"
uri = "file://exports/truck-wrap/f250-rear-tailgate.png"
type = "image"
title = "F-250 Wrap Mockup — Rear Tailgate"

[[outputs]]
id = "uy-BwwWoWAWZNIrN_CDjO"
uri = "file://exports/google-business/willwork.jpg"
type = "image"
title = "Will Work Construction — website"

[[outputs]]
id = "fOA66DI_xTJ5Dexs7epiP"
uri = "file://exports/google-business/landons-cleaning.jpg"
type = "image"
title = "Landon's Cleaning Co. — website"

[[outputs]]
id = "FbEfxfQrnDq1tOMEc4eGY"
uri = "file://exports/google-business/panjos.jpg"
type = "image"
title = "Panjo's Pizza — website"

[[outputs]]
id = "yIitbamU9Z-Y57xF-pQW1"
uri = "file://exports/google-business/comic.jpg"
type = "image"
title = "Comic Mystery Boxes — website"

[[outputs]]
id = "BAY5VbV1YWb5wPTT4lZTv"
uri = "file://exports/google-business/theraid.jpg"
type = "image"
title = "The Raid — website"

[[outputs]]
id = "XryUXB7vaVIMhSWUzD8L9"
uri = "file://exports/google-business/keyplus.jpg"
type = "image"
title = "Key Plus — website"

[[outputs]]
id = "1b2145_6dQQDlYDfQwjo3"
uri = "file://exports/google-business/moose-and-the-bear.jpg"
type = "image"
title = "Moose & the Bear — website"

[[outputs]]
id = "TLFnBRaHOahL-4xRR6CBE"
uri = "file://exports/google-business/dlt-custom-homes.jpg"
type = "image"
title = "DLT Custom Homes — website"
